# Урок 2 Numpy

# Задание 1

In [1]:
import numpy as np

In [2]:
b = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
print(b)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [3]:
a = b.T
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [4]:
mean_a=np.mean(a,0)
print(mean_a)

[2.  8.4]


# Задание 2

In [5]:
a_centered = a-mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


# Задание 3

In [6]:
a_centered_sp= np.dot(np.take(a_centered,0,1),np.take(a,1,1))
print(a_centered_sp)

8.0


In [7]:
a_centered_sp/4

2.0

# Задание 4

In [9]:
print(np.cov(b)[0:1,1:])



[[2.]]
